export const FETCH_PRODUCT_FAILED='FETCH_PRODUCT_FAILED'
 export const FETCH_PRODUCT_LOADING='FETCH_PRODUCT_LOADING'
 export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS'
 export const ADD_TO_CART = 'ADD_TO_CART';
